schema-version = "1.11.0"


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
devcontainer.pkg-path = "devcontainer"
# gum.pkg-path = "gum"
# gum.version = "^0.14.5"


## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"


## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
on-activate = '''
'''


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
common = '''
# symlink the shared .devcontainer into the current directory
alias devc='ln -s ~/workspaces/devcontainers/.devcontainer .devcontainer'
alias devc-cp='cp -R ~/workspaces/devcontainers/.devcontainer .'
'''

## Shell-specific customizations such as setting aliases go here:
# bash = ...
zsh  = '''
if [[ "$(uname -s)" == "Darwin" ]]; then
  chpwd() {
    if [ -d ".devcontainer" ] && [ -z "$INSIDE_DEVCONTAINER" ]; then
     echo "🐳 Starting devcontainer and connecting..."
     devcontainer up --workspace-folder . && \
     INSIDE_DEVCONTAINER=1 devcontainer exec --workspace-folder . bash
   fi
  }
fi
'''
# fish = ...


## Services ---------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## ------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Include ----------------------------------------------------------
## ... environments to create a composed environment
## ------------------------------------------------------------------
[include]
# environments = [
#     { dir = "../common" }
# ]


## Build and publish your own packages ------------------------------
##  $ flox build
##  $ flox publish
## ------------------------------------------------------------------
[build]
# [build.myproject]
# description = "The coolest project ever"
# version = "0.0.1"
# command = """
#   mkdir -p $out/bin
#   cargo build --release
#   cp target/release/myproject $out/bin/myproject
# """


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = [
   "aarch64-darwin",
#   "aarch64-linux",
#   "x86_64-darwin",
#   "x86_64-linux",
]
# Uncomment to disable CUDA detection.
cuda-detection = false
